name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  # Biến này sẽ có thể được sử dụng bởi tất cả các job
  # MONGODB_DB_NAME: gha-demo
  MONGODB_CLUSTER_ADDRESS: cluster0.ay6rlxm.mongodb.net
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}

jobs:
  test:
    env: 
      
      MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
      MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
      PORT: 8800
    environment: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://localhost:$PORT
      - name: Run tests
        run: npm test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=cuong199344
              -Dsonar.projectKey=cuong199344
              -Dsonar.python.coverage.reportPaths=coverage.xml
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MONGODB_USERNAME: ${{env.MONGODB_USERNAME}}"
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
